Solution for lists
ALEXANCHESSS/eu-python-learn-challenge pull request #1
Opened 2024-05-09 09:46 UTC by ALEXANCHESSS

2024-05-12 23:04 UTC, aleksandr-semenov-dbp requested changes

2024-05-12 23:04 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        for i in input_list:
i нормальное имя для индекса, но для элемента имя неудачное, запутывает

2024-05-12 23:04 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        max: int = 0
поиск максимума лучше начинать с первого элемента, а не с какого-то фиксированного значения

2024-05-12 23:04 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        else:
после return не нужно else, мы стремимся уменьшать количество отступов для читаемости

2024-05-12 23:04 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        def start_search(low: int, mid: int, high: int) -> int:
Эта функция может рассчитать mid сама, когда он ей понадобится, незачем передавать его. и тогда расчет будет в одном месте а не в трех

2024-05-12 23:04 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            elif input_list[mid] == query:
тут тоже можно везде убрать else/заменить elif на if после return

2024-05-13 09:45 UTC, ALEXANCHESSS commented on lists/lists.py
> +            elif input_list[mid] == query:
Но если мы уберем else, то не пройдет линтер:
`error: Missing return statement`

2024-05-20 06:39 UTC, aleksandr-semenov-dbp approved these changes

2024-05-20 06:39 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            return input_list
```
if not input_list:
  return []
max = input_list[0]
```
на строку короче, меньше лесенок отступов

2024-05-20 06:39 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            elif input_list[mid] == query:
Звучит странно. Я не retuкn-ы предлагаю убирать а elsы, не должен линтер ругаться если return-ов хватает.

2024-05-20 09:37 UTC, merged